// Sand-DOS v3.1 Comprehensive Sandbox Element Registry & Reaction Physics

export const ELEMENT_IDS = {
  EMPTY: 0,
  SAND: 1,
  WATER: 2,
  OIL: 3,
  FIRE: 4,
  PLANT: 5,
  STONE: 6,
  ACID: 7,
  LAVA: 8,
  GUNPOWDER: 9,
  C4: 10,
  ICE: 11,
  STEAM: 12,
  SMOKE: 13,
  SPOUT_SAND: 14,
  SPOUT_WATER: 15,
  SPOUT_OIL: 16,
  SPOUT_LAVA: 17,
  CLONER: 18,
  VOID: 19,
  SPARK: 20,
  GLASS: 21,
  LASER: 22,
  WAX: 23,
  LIQUID_WAX: 24,
  MITE: 25,
  TNT: 26,
  PORTAL_A: 27,
  PORTAL_B: 28,
  SPOUT_ACID: 29,
  GAS_FUEL: 30,

  // --- Electricity & Electronics ---
  WIRE: 31,
  BATTERY: 32,
  SWITCH_OFF: 33,
  SWITCH_ON: 34,
  HEATER: 35,
  COOLER: 36,
  ANTIMATTER: 37,
  LIGHTNING: 38,

  // --- Advanced Materials & Chemistry ---
  IRON: 39,
  RUST: 40,
  MERCURY: 41,
  SALT: 42,
  SALTWATER: 43,
  MUD: 44,
  CEMENT: 45,
  CONCRETE: 46,
  FUNGUS: 47,
  CHARCOAL: 48,
  SPARK_ELEC: 49,
};

export const ELEMENT_CATEGORIES = {
  POWDERS: 'Powders',
  LIQUIDS: 'Liquids',
  GASES: 'Gases',
  SOLIDS: 'Solids',
  EXPLOSIVES: 'Explosives',
  ELECTRICITY: 'Electricity',
  MATERIALS: 'Materials & Chem',
  LIFE_TECH: 'Life & Tech',
  SPECIAL: 'Special & Tools',
};

export const ELEMENTS = {
  [ELEMENT_IDS.EMPTY]: {
    id: ELEMENT_IDS.EMPTY,
    name: 'Air / Vacuum',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Empty space',
    color: [12, 16, 32, 255],
    density: 0,
    temp: 20, // 20°C ambient room temperature
    type: 'empty',
    hotkey: '0',
  },

  [ELEMENT_IDS.SAND]: {
    id: ELEMENT_IDS.SAND,
    name: 'Sand',
    category: ELEMENT_CATEGORIES.POWDERS,
    description: 'Heavy granular powder. Cascades into dunes, melts into Glass at high heat.',
    color: [225, 185, 95, 255],
    colorVariants: [
      [235, 195, 105, 255],
      [220, 180, 85, 255],
      [205, 165, 75, 255],
      [245, 205, 115, 255],
    ],
    density: 10,
    temp: 20,
    type: 'powder',
    hotkey: '1',
  },

  [ELEMENT_IDS.WATER]: {
    id: ELEMENT_IDS.WATER,
    name: 'Water',
    category: ELEMENT_CATEGORIES.LIQUIDS,
    description: 'Fluid liquid. Freezes into Ice at 0°C, boils into Steam at 100°C.',
    color: [40, 140, 240, 220],
    colorVariants: [
      [35, 130, 230, 220],
      [50, 150, 250, 220],
      [30, 120, 220, 220],
      [60, 160, 255, 220],
    ],
    density: 5,
    dispersion: 5,
    temp: 20,
    type: 'liquid',
    hotkey: '2',
  },

  [ELEMENT_IDS.OIL]: {
    id: ELEMENT_IDS.OIL,
    name: 'Oil',
    category: ELEMENT_CATEGORIES.LIQUIDS,
    description: 'Viscous crude oil. Floats on water, ignites into wild fire.',
    color: [140, 100, 30, 240],
    colorVariants: [
      [130, 90, 25, 240],
      [150, 110, 35, 240],
    ],
    density: 3,
    dispersion: 3,
    temp: 20,
    type: 'liquid',
    flammable: true,
    hotkey: '3',
  },

  [ELEMENT_IDS.FIRE]: {
    id: ELEMENT_IDS.FIRE,
    name: 'Fire',
    category: ELEMENT_CATEGORIES.GASES,
    description: 'Hot plasma (400°C). Ignites fuels, melts ice/wax, generates smoke.',
    color: [255, 90, 20, 255],
    colorVariants: [
      [255, 140, 10, 255],
      [255, 60, 0, 255],
      [255, 210, 50, 255],
    ],
    density: -1,
    glow: true,
    temp: 400,
    type: 'gas',
    lifeMin: 14,
    lifeMax: 30,
    hotkey: '4',
  },

  [ELEMENT_IDS.PLANT]: {
    id: ELEMENT_IDS.PLANT,
    name: 'Plant / Wood',
    category: ELEMENT_CATEGORIES.SOLIDS,
    description: 'Combustible organic material. Grows when absorbing water, burns into Charcoal.',
    color: [45, 170, 60, 255],
    colorVariants: [
      [40, 155, 55, 255],
      [55, 185, 70, 255],
      [35, 140, 45, 255],
    ],
    density: 100,
    temp: 20,
    type: 'solid',
    flammable: true,
    hotkey: '5',
  },

  [ELEMENT_IDS.STONE]: {
    id: ELEMENT_IDS.STONE,
    name: 'Stone Wall',
    category: ELEMENT_CATEGORIES.SOLIDS,
    description: 'Rigid barrier wall. Melts into Lava at 1000°C.',
    color: [140, 145, 155, 255],
    colorVariants: [
      [130, 135, 145, 255],
      [150, 155, 165, 255],
    ],
    density: 1000,
    temp: 20,
    type: 'solid',
    hotkey: '6',
  },

  [ELEMENT_IDS.ACID]: {
    id: ELEMENT_IDS.ACID,
    name: 'Acid',
    category: ELEMENT_CATEGORIES.LIQUIDS,
    description: 'Corrosive chemical liquid. Melts solids & liquids into acid vapor.',
    color: [120, 255, 30, 240],
    colorVariants: [
      [110, 240, 20, 240],
      [135, 255, 50, 240],
    ],
    density: 6,
    dispersion: 4,
    temp: 30,
    type: 'liquid',
    hotkey: '7',
  },

  [ELEMENT_IDS.LAVA]: {
    id: ELEMENT_IDS.LAVA,
    name: 'Lava',
    category: ELEMENT_CATEGORIES.LIQUIDS,
    description: 'Molten magma (1200°C). Ignites surroundings, cools into Stone with water.',
    color: [255, 60, 10, 255],
    colorVariants: [
      [240, 40, 0, 255],
      [255, 110, 20, 255],
      [255, 170, 50, 255],
    ],
    density: 8,
    dispersion: 2,
    glow: true,
    temp: 1200,
    type: 'liquid',
    hotkey: '8',
  },

  [ELEMENT_IDS.GUNPOWDER]: {
    id: ELEMENT_IDS.GUNPOWDER,
    name: 'Gunpowder',
    category: ELEMENT_CATEGORIES.EXPLOSIVES,
    description: 'Volatile explosive powder. Rapid chain reaction explosion on heat/spark.',
    color: [75, 80, 85, 255],
    colorVariants: [
      [65, 70, 75, 255],
      [85, 90, 95, 255],
    ],
    density: 9,
    temp: 20,
    type: 'powder',
    flammable: true,
    explosive: true,
    hotkey: '9',
  },

  [ELEMENT_IDS.C4]: {
    id: ELEMENT_IDS.C4,
    name: 'C4 Explosive',
    category: ELEMENT_CATEGORIES.EXPLOSIVES,
    description: 'High-yield explosive block. Detonates in a wide shockwave blast.',
    color: [210, 195, 150, 255],
    density: 500,
    temp: 20,
    type: 'solid',
    flammable: true,
    explosive: true,
    hotkey: 'C',
  },

  [ELEMENT_IDS.ICE]: {
    id: ELEMENT_IDS.ICE,
    name: 'Ice',
    category: ELEMENT_CATEGORIES.SOLIDS,
    description: 'Frozen water (-10°C). Freezes water, melts into Water above 0°C.',
    color: [175, 225, 255, 220],
    colorVariants: [
      [160, 215, 250, 220],
      [190, 235, 255, 220],
    ],
    density: 950,
    temp: -10,
    type: 'solid',
    hotkey: 'I',
  },

  [ELEMENT_IDS.STEAM]: {
    id: ELEMENT_IDS.STEAM,
    name: 'Steam',
    category: ELEMENT_CATEGORIES.GASES,
    description: 'Hot vapor moisture (110°C). Rises quickly, condenses into Water when cool.',
    color: [210, 230, 245, 160],
    density: -2,
    temp: 110,
    type: 'gas',
    lifeMin: 40,
    lifeMax: 90,
    hotkey: 'V',
  },

  [ELEMENT_IDS.SMOKE]: {
    id: ELEMENT_IDS.SMOKE,
    name: 'Smoke',
    category: ELEMENT_CATEGORIES.GASES,
    description: 'Dark carbon smoke gas. Rises slowly and dissipates.',
    color: [90, 95, 105, 180],
    density: -1,
    temp: 80,
    type: 'gas',
    lifeMin: 30,
    lifeMax: 75,
    hotkey: 'M',
  },

  [ELEMENT_IDS.GLASS]: {
    id: ELEMENT_IDS.GLASS,
    name: 'Glass Window',
    category: ELEMENT_CATEGORIES.SOLIDS,
    description: 'Translucent acid-proof & fireproof solid wall. Shatters under heavy blast.',
    color: [200, 235, 245, 180],
    density: 1000,
    temp: 20,
    type: 'solid',
    hotkey: 'G',
  },

  [ELEMENT_IDS.LASER]: {
    id: ELEMENT_IDS.LASER,
    name: 'Laser Emitter',
    category: ELEMENT_CATEGORIES.LIFE_TECH,
    description: 'High-energy beam tile. Emits intense hot laser ray that melts & ignites target.',
    color: [255, 0, 100, 255],
    density: 1000,
    glow: true,
    temp: 800,
    type: 'solid',
    hotkey: 'Z',
  },

  [ELEMENT_IDS.WAX]: {
    id: ELEMENT_IDS.WAX,
    name: 'Wax',
    category: ELEMENT_CATEGORIES.SOLIDS,
    description: 'Solid paraffin wax. Melts into Liquid Wax at 50°C.',
    color: [240, 230, 190, 255],
    density: 850,
    temp: 20,
    type: 'solid',
  },

  [ELEMENT_IDS.LIQUID_WAX]: {
    id: ELEMENT_IDS.LIQUID_WAX,
    name: 'Liquid Wax',
    category: ELEMENT_CATEGORIES.LIQUIDS,
    description: 'Molten liquid wax. Solidifies into Wax block below 40°C.',
    color: [230, 210, 150, 230],
    density: 4,
    dispersion: 3,
    temp: 60,
    type: 'liquid',
  },

  [ELEMENT_IDS.MITE]: {
    id: ELEMENT_IDS.MITE,
    name: 'Bug / Mite',
    category: ELEMENT_CATEGORIES.LIFE_TECH,
    description: 'Living bug pixel! Crawls along surfaces, eats plants/fungus to reproduce.',
    color: [255, 200, 0, 255],
    density: 15,
    temp: 25,
    type: 'powder',
    hotkey: 'B',
  },

  [ELEMENT_IDS.TNT]: {
    id: ELEMENT_IDS.TNT,
    name: 'TNT Dynamite',
    category: ELEMENT_CATEGORIES.EXPLOSIVES,
    description: 'Dynamite block with fuse line trigger.',
    color: [220, 40, 30, 255],
    density: 600,
    temp: 20,
    type: 'solid',
    flammable: true,
    explosive: true,
    hotkey: 'T',
  },

  [ELEMENT_IDS.PORTAL_A]: {
    id: ELEMENT_IDS.PORTAL_A,
    name: 'Portal Blue (A)',
    category: ELEMENT_CATEGORIES.LIFE_TECH,
    description: 'Quantum entrance portal. Teleports elements to Portal Orange (B)!',
    color: [0, 150, 255, 255],
    density: 1000,
    glow: true,
    type: 'solid',
  },

  [ELEMENT_IDS.PORTAL_B]: {
    id: ELEMENT_IDS.PORTAL_B,
    name: 'Portal Orange (B)',
    category: ELEMENT_CATEGORIES.LIFE_TECH,
    description: 'Quantum exit portal. Outputs elements arriving from Portal Blue (A)!',
    color: [255, 140, 0, 255],
    density: 1000,
    glow: true,
    type: 'solid',
  },

  [ELEMENT_IDS.GAS_FUEL]: {
    id: ELEMENT_IDS.GAS_FUEL,
    name: 'LPG Gas Fuel',
    category: ELEMENT_CATEGORIES.GASES,
    description: 'Invisible combustible gas fuel. Floats upwards, explodes into fire storm.',
    color: [180, 100, 255, 140],
    density: -3,
    temp: 20,
    type: 'gas',
    lifeMin: 60,
    lifeMax: 140,
    hotkey: 'F',
  },

  // --- ELECTRICITY & ELECTRONICS ---

  [ELEMENT_IDS.WIRE]: {
    id: ELEMENT_IDS.WIRE,
    name: 'Copper Wire',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Conductive wire. Transmits electrical charge to connected components.',
    color: [210, 120, 50, 255],
    colorVariants: [
      [220, 130, 60, 255],
      [200, 110, 40, 255],
    ],
    density: 1000,
    conductive: true,
    type: 'solid',
    hotkey: 'E',
  },

  [ELEMENT_IDS.BATTERY]: {
    id: ELEMENT_IDS.BATTERY,
    name: 'Battery Generator',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Power source. Emits continuous electricity into adjacent wires.',
    color: [50, 200, 50, 255],
    density: 1000,
    conductive: true,
    powerSource: true,
    type: 'solid',
    hotkey: 'R',
  },

  [ELEMENT_IDS.SWITCH_OFF]: {
    id: ELEMENT_IDS.SWITCH_OFF,
    name: 'Switch (OFF)',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Electrical switch (OFF). Click on canvas to toggle ON/OFF.',
    color: [180, 50, 50, 255],
    density: 1000,
    type: 'solid',
  },

  [ELEMENT_IDS.SWITCH_ON]: {
    id: ELEMENT_IDS.SWITCH_ON,
    name: 'Switch (ON)',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Electrical switch (ON). Conducts power when activated.',
    color: [50, 220, 80, 255],
    density: 1000,
    conductive: true,
    type: 'solid',
  },

  [ELEMENT_IDS.HEATER]: {
    id: ELEMENT_IDS.HEATER,
    name: 'Electrical Heater',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Powered element. Heats up to 500°C when electricity passes through!',
    color: [255, 100, 50, 255],
    density: 1000,
    conductive: true,
    type: 'solid',
    hotkey: 'H',
  },

  [ELEMENT_IDS.COOLER]: {
    id: ELEMENT_IDS.COOLER,
    name: 'Thermo Cooler',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Powered element. Freezes surroundings down to -50°C when powered!',
    color: [50, 200, 255, 255],
    density: 1000,
    conductive: true,
    type: 'solid',
  },

  [ELEMENT_IDS.ANTIMATTER]: {
    id: ELEMENT_IDS.ANTIMATTER,
    name: 'Antimatter',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'Annihilates any matter cell it touches, releasing high energy flashes.',
    color: [255, 0, 255, 255],
    glow: true,
    density: -5,
    type: 'powder',
  },

  [ELEMENT_IDS.LIGHTNING]: {
    id: ELEMENT_IDS.LIGHTNING,
    name: 'Lightning Strike',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'High-voltage plasma arc (2000°C). Electrifies conductors and detonates explosives.',
    color: [255, 255, 200, 255],
    glow: true,
    temp: 2000,
    density: -1,
    type: 'gas',
    lifeMin: 2,
    lifeMax: 5,
  },

  // --- ADVANCED MATERIALS & CHEMISTRY ---

  [ELEMENT_IDS.IRON]: {
    id: ELEMENT_IDS.IRON,
    name: 'Iron Metal',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Conductive metallic block. Rusts when exposed to Water & Acid.',
    color: [160, 165, 175, 255],
    density: 1000,
    conductive: true,
    temp: 20,
    type: 'solid',
  },

  [ELEMENT_IDS.RUST]: {
    id: ELEMENT_IDS.RUST,
    name: 'Rust',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Corroded iron oxide powder. Weak structural integrity.',
    color: [180, 80, 40, 255],
    density: 8,
    temp: 20,
    type: 'powder',
  },

  [ELEMENT_IDS.MERCURY]: {
    id: ELEMENT_IDS.MERCURY,
    name: 'Mercury',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Heavy toxic metal liquid (Density 13). Sinks below all liquids including Lava.',
    color: [200, 205, 215, 255],
    density: 13,
    dispersion: 4,
    conductive: true,
    temp: 20,
    type: 'liquid',
  },

  [ELEMENT_IDS.SALT]: {
    id: ELEMENT_IDS.SALT,
    name: 'Salt',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'White mineral powder. Dissolves in Water to form conductive Saltwater.',
    color: [245, 245, 250, 255],
    density: 7,
    temp: 20,
    type: 'powder',
  },

  [ELEMENT_IDS.SALTWATER]: {
    id: ELEMENT_IDS.SALTWATER,
    name: 'Saltwater',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Saline conductive water. Highly conductive to electricity and melts ice fast.',
    color: [30, 170, 240, 230],
    density: 6,
    dispersion: 5,
    conductive: true,
    temp: 20,
    type: 'liquid',
  },

  [ELEMENT_IDS.MUD]: {
    id: ELEMENT_IDS.MUD,
    name: 'Mud',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Wet earth mixture (Sand + Water). Bakes into Clay/Brick at high heat.',
    color: [110, 75, 45, 255],
    density: 7,
    dispersion: 1,
    temp: 20,
    type: 'liquid',
  },

  [ELEMENT_IDS.CEMENT]: {
    id: ELEMENT_IDS.CEMENT,
    name: 'Liquid Cement',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Viscous slurry liquid. Hardens over time into unbreakable Concrete!',
    color: [160, 160, 150, 255],
    density: 9,
    dispersion: 2,
    temp: 20,
    type: 'liquid',
  },

  [ELEMENT_IDS.CONCRETE]: {
    id: ELEMENT_IDS.CONCRETE,
    name: 'Concrete',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Hardened structural concrete block. Immune to explosions and acid.',
    color: [120, 125, 130, 255],
    density: 2000,
    temp: 20,
    type: 'solid',
  },

  [ELEMENT_IDS.FUNGUS]: {
    id: ELEMENT_IDS.FUNGUS,
    name: 'Spreading Fungus',
    category: ELEMENT_CATEGORIES.LIFE_TECH,
    description: 'Purple organic spore. Spreads across plant and wood turning them into fungus.',
    color: [160, 50, 200, 255],
    density: 50,
    temp: 20,
    type: 'solid',
  },

  [ELEMENT_IDS.CHARCOAL]: {
    id: ELEMENT_IDS.CHARCOAL,
    name: 'Charcoal',
    category: ELEMENT_CATEGORIES.MATERIALS,
    description: 'Burned wood residue powder. Slow-burning fuel.',
    color: [40, 42, 45, 255],
    density: 6,
    temp: 20,
    type: 'powder',
    flammable: true,
  },

  [ELEMENT_IDS.SPARK_ELEC]: {
    id: ELEMENT_IDS.SPARK_ELEC,
    name: 'Electrical Spark',
    category: ELEMENT_CATEGORIES.ELECTRICITY,
    description: 'High voltage electrical charge traveling along conductor wires.',
    color: [255, 255, 100, 255],
    glow: true,
    density: -1,
    temp: 300,
    type: 'gas',
    lifeMin: 2,
    lifeMax: 4,
  },

  // Spout Emitters
  [ELEMENT_IDS.SPOUT_SAND]: {
    id: ELEMENT_IDS.SPOUT_SAND,
    name: 'Sand Spout',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Infinite sand fountain block.',
    color: [225, 160, 40, 255],
    density: 1000,
    type: 'solid',
    spawns: ELEMENT_IDS.SAND,
    hotkey: 'S',
  },

  [ELEMENT_IDS.SPOUT_WATER]: {
    id: ELEMENT_IDS.SPOUT_WATER,
    name: 'Water Spout',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Infinite water fountain block.',
    color: [0, 180, 255, 255],
    density: 1000,
    type: 'solid',
    spawns: ELEMENT_IDS.WATER,
    hotkey: 'W',
  },

  [ELEMENT_IDS.SPOUT_OIL]: {
    id: ELEMENT_IDS.SPOUT_OIL,
    name: 'Oil Spout',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Infinite petroleum spout block.',
    color: [180, 130, 20, 255],
    density: 1000,
    type: 'solid',
    spawns: ELEMENT_IDS.OIL,
    hotkey: 'O',
  },

  [ELEMENT_IDS.SPOUT_LAVA]: {
    id: ELEMENT_IDS.SPOUT_LAVA,
    name: 'Lava Spout',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Magma volcano spout block.',
    color: [255, 40, 0, 255],
    density: 1000,
    type: 'solid',
    spawns: ELEMENT_IDS.LAVA,
    hotkey: 'L',
  },

  [ELEMENT_IDS.SPOUT_ACID]: {
    id: ELEMENT_IDS.SPOUT_ACID,
    name: 'Acid Spout',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Corrosive acid generator block.',
    color: [100, 230, 20, 255],
    density: 1000,
    type: 'solid',
    spawns: ELEMENT_IDS.ACID,
    hotkey: 'A',
  },

  [ELEMENT_IDS.CLONER]: {
    id: ELEMENT_IDS.CLONER,
    name: 'Cloner',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Duplicates any element touching its upper boundary!',
    color: [210, 40, 220, 255],
    density: 1000,
    type: 'solid',
    hotkey: 'K',
  },

  [ELEMENT_IDS.VOID]: {
    id: ELEMENT_IDS.VOID,
    name: 'Black Hole (Void)',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Consumes any element that touches its event horizon.',
    color: [40, 10, 60, 255],
    density: 1000,
    type: 'solid',
    hotkey: 'D',
  },

  [ELEMENT_IDS.SPARK]: {
    id: ELEMENT_IDS.SPARK,
    name: 'Spark',
    category: ELEMENT_CATEGORIES.SPECIAL,
    description: 'Burning ember spark particle.',
    color: [255, 255, 180, 255],
    density: -1,
    glow: true,
    type: 'gas',
    lifeMin: 3,
    lifeMax: 10,
  },
};

export function getElementColor(id, variantSeed = 0) {
  const elem = ELEMENTS[id] || ELEMENTS[ELEMENT_IDS.EMPTY];
  if (elem.colorVariants && elem.colorVariants.length > 0) {
    const idx = Math.abs(variantSeed) % elem.colorVariants.length;
    return elem.colorVariants[idx];
  }
  return elem.color;
}
